version: '3.7'

services:
  database: 
    image: mysql:5.7.22
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init/todo.sql:/docker-entrypoint-initdb.d/todo.sql
    environment: 
      MYSQL_DATABASE: todo
      MYSQL_USER: apptodo
      MYSQL_PASSWORD: todo
      MYSQL_ROOT_PASSWORD: todo
    networks:
      - app

  todo:
    container_name: todo
    build:
      context: .
      dockerfile: ./todo/.docker/Dockerfile
    restart: always
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    volumes:
      - ./todo:/var/www
    working_dir: /var/www
    command: ["/wait-for-it.sh", "database:3308", "--", "/build.sh"]
    tty: true
    networks:
      - app
    ports:
      - "9000:9000"

  todo_proxy:
    container_name: todo_proxy
    build:
      context: .
      dockerfile: ./todo/.docker/Dockerfile.proxy
    restart: unless-stopped
    volumes:
      - ./my-vue:/var/www
    command: ["/wait-for-it.sh", "todo:9000", "--", "nginx", "-g", "daemon off;"]
    tty: true
    networks:
      - app
    ports:
      - "80:80"
      - "443:443"

  my-vue:
    container_name: my-vue
    build:
      context: .
      dockerfile: ./my-vue/.docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./my-vue:/app
    working_dir: /app
    command: ["/wait-for-it.sh", "todo_proxy:80", "--", "/build.sh"]
    tty: true
    networks:
      - app
    ports:
      - "8080:8080"
    depends_on:
      - todo_proxy
      - database
      - todo

networks:
  app:
    driver: bridge
